apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: bbx-vol-test
  name: bbx-vol-test
spec:
  replicas: 1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: bbx-vol-test
        deploymentconfig: bbx-vol-test
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Volume Test is running! && touch /mnt/vol-test-\`uname -n\` && ls -l /mnt && sleep 300
        image: busybox:latest
        imagePullPolicy: Always
        name: bbx-vol-test
        resources: {}
        volumeMounts:
        - mountPath: /mnt
          name: vol1
      restartPolicy: Always
      securityContext: {}
      volumes:
      - emptyDir: {}
        name: vol1
  triggers:
  - type: ConfigChange
